export default {
  CHANGE_CHARACTER_COLOR: 'CHANGE_CHARACTER_COLOR',
  SET_CHARACTER_POSITION: 'SET_CHARACTER_POSITION',
  MOVE_CHARACTER_LEFT: 'MOVE_CHARACTER_LEFT',
  MOVE_CHARACTER_RIGHT: 'MOVE_CHARACTER_RIGHT',
  MOVE_CHARACTER_UP: 'MOVE_CHARACTER_UP',
  MOVE_CHARACTER_DOWN: 'MOVE_CHARACTER_DOWN',
};
